server:
  port: 8080
spring:
  application:
    name: GoodShops
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prod?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    host: localhost
    password: 123456
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  profiles:
    active: prod
mybatis:
  #别名包（方便在映射文件中直接写类名）
  type-aliases-package: org.nefure.goodshops.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.nefure.goodshops: debug